// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.9.2+v0.28.3
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
namespace uniffi.sylva_sdk;



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_sylva_sdk_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_sylva_sdk_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
internal class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

internal class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

internal class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

internal class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

internal class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

internal class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

internal class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

internal class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: UniffiException
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: UniffiException
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        foreach (var obj in list) {
            Dispose(obj);
        }
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
            //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
            //for all keys as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
            //This extra code tests to not call "Dispose" for a List<int>()
            //for all keys as "int" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[0];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if DOTNET_8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if DOTNET_8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer) {
#if DOTNET_8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();
    public short ReadShort() => (short)ReadUShort();
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
static class _UniFFILib {
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFuture
    {
        public ulong @handle;
        public IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructPointer
    {
        public IntPtr @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompletePointer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructPointer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureStructVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureStructVoid @result
    );
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        }

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr uniffi_sylva_sdk_fn_clone_sylvaclient(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_sylva_sdk_fn_free_sylvaclient(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr uniffi_sylva_sdk_fn_constructor_sylvaclient_new(RustBuffer @service,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_sylva_sdk_fn_method_sylvaclient_connect(IntPtr @ptr,RustBuffer @host,ushort @discoveryPort,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_sylva_sdk_fn_method_sylvaclient_create_owner(IntPtr @ptr,RustBuffer @email,RustBuffer @displayName,RustBuffer @password,RustBuffer @deviceLabel,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_sylva_sdk_fn_method_sylvaclient_enroll_this_device(IntPtr @ptr,RustBuffer @label,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_sylva_sdk_fn_method_sylvaclient_forget_server(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_sylva_sdk_fn_method_sylvaclient_list_devices(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_sylva_sdk_fn_method_sylvaclient_restore(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_sylva_sdk_fn_method_sylvaclient_revoke_device(IntPtr @ptr,RustBuffer @deviceId,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer uniffi_sylva_sdk_fn_method_sylvaclient_sign_in(IntPtr @ptr,RustBuffer @email,RustBuffer @password,RustBuffer @secretKey,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void uniffi_sylva_sdk_fn_method_sylvaclient_sign_out(IntPtr @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_sylva_sdk_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_sylva_sdk_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_sylva_sdk_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_u8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_u8(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_u8(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte ffi_sylva_sdk_rust_future_complete_u8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_i8(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_i8(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_i8(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern sbyte ffi_sylva_sdk_rust_future_complete_i8(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_u16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_u16(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_u16(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort ffi_sylva_sdk_rust_future_complete_u16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_i16(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_i16(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_i16(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern short ffi_sylva_sdk_rust_future_complete_i16(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_u32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_u32(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_u32(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_sylva_sdk_rust_future_complete_u32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_i32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_i32(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_i32(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern int ffi_sylva_sdk_rust_future_complete_i32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_u64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_u64(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_u64(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ulong ffi_sylva_sdk_rust_future_complete_u64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_i64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_i64(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_i64(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern long ffi_sylva_sdk_rust_future_complete_i64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_f32(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_f32(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_f32(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern float ffi_sylva_sdk_rust_future_complete_f32(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_f64(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_f64(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_f64(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern double ffi_sylva_sdk_rust_future_complete_f64(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_pointer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_pointer(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_pointer(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ffi_sylva_sdk_rust_future_complete_pointer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_rust_buffer(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_rust_buffer(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_rust_buffer(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern RustBuffer ffi_sylva_sdk_rust_future_complete_rust_buffer(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_poll_void(IntPtr @handle,IntPtr @callback,IntPtr @callbackData
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_cancel_void(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_free_void(IntPtr @handle
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ffi_sylva_sdk_rust_future_complete_void(IntPtr @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_connect(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_create_owner(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_enroll_this_device(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_forget_server(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_list_devices(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_restore(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_revoke_device(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_sign_in(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_method_sylvaclient_sign_out(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern ushort uniffi_sylva_sdk_checksum_constructor_sylvaclient_new(
    );

    [DllImport("sylva_sdk", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint ffi_sylva_sdk_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_sylva_sdk_uniffi_contract_version();
        if (26 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"uniffi.sylva_sdk: uniffi bindings expected version `26`, library returned `{scaffolding_contract_version}`");
        }
    }

    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_connect();
            if (checksum != 16991) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_connect` checksum `16991`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_create_owner();
            if (checksum != 18614) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_create_owner` checksum `18614`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_enroll_this_device();
            if (checksum != 17119) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_enroll_this_device` checksum `17119`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_forget_server();
            if (checksum != 20078) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_forget_server` checksum `20078`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_list_devices();
            if (checksum != 36386) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_list_devices` checksum `36386`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_restore();
            if (checksum != 30185) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_restore` checksum `30185`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_revoke_device();
            if (checksum != 36160) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_revoke_device` checksum `36160`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_sign_in();
            if (checksum != 1315) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_sign_in` checksum `1315`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_method_sylvaclient_sign_out();
            if (checksum != 6896) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_method_sylvaclient_sign_out` checksum `6896`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_sylva_sdk_checksum_constructor_sylvaclient_new();
            if (checksum != 13705) {
                throw new UniffiContractChecksumException($"uniffi.sylva_sdk: uniffi bindings expected function `uniffi_sylva_sdk_checksum_constructor_sylvaclient_new` checksum `13705`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterUInt16: FfiConverter<ushort, ushort> {
    public static FfiConverterUInt16 INSTANCE = new FfiConverterUInt16();

    public override ushort Lift(ushort value) {
        return value;
    }

    public override ushort Read(BigEndianStream stream) {
        return stream.ReadUShort();
    }

    public override ushort Lower(ushort value) {
        return value;
    }

    public override int AllocationSize(ushort value) {
        return 2;
    }

    public override void Write(ushort value, BigEndianStream stream) {
        stream.WriteUShort(value);
    }
}



class FfiConverterBoolean: FfiConverter<bool, sbyte> {
    public static FfiConverterBoolean INSTANCE = new FfiConverterBoolean();

    public override bool Lift(sbyte value) {
        return value != 0;
    }

    public override bool Read(BigEndianStream stream) {
        return Lift(stream.ReadSByte());
    }

    public override sbyte Lower(bool value) {
        return value ? (sbyte)1 : (sbyte)0;
    }

    public override int AllocationSize(bool value) {
        return (sbyte)1;
    }

    public override void Write(bool value, BigEndianStream stream) {
        stream.WriteSByte(Lower(value));
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}



/// <summary>
/// The shell-facing handle: a blocking wrapper over the async [`Client`] facade
/// with its own runtime. Held for the app's lifetime.
/// </summary>
internal interface ISylvaClient {
    /// <summary>
    /// Discover + verify + connect a server (TOFU). See [`Client::connect`].
    /// </summary>
    /// <exception cref="ClientException"></exception>
    ConnectInfo Connect(string @host, ushort @discoveryPort);
    /// <summary>
    /// Create the first owner. Returns the Secret Key to show once.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    Enrollment CreateOwner(string @email, string @displayName, string @password, string @deviceLabel);
    /// <summary>
    /// Enroll this device into the signed-in account.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    DeviceInfo EnrollThisDevice(string @label);
    /// <summary>
    /// Forget this server entirely — full wipe; re-enroll (Secret Key) to return
    /// (see [`Client::forget_server`]).
    /// </summary>
    /// <exception cref="ClientException"></exception>
    void ForgetServer();
    /// <summary>
    /// This account's active devices.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    List<DeviceInfo> ListDevices();
    /// <summary>
    /// Auto-resume a prior session on launch (see [`Client::restore`]). Returns the
    /// user id if resumed, else `None` (the shell then shows Connect).
    /// </summary>
    /// <exception cref="ClientException"></exception>
    string? Restore();
    /// <summary>
    /// Revoke one of this account's devices.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    void RevokeDevice(string @deviceId);
    /// <summary>
    /// Sign in (+ unlock). `secret_key` is the user-entered value on a new
    /// device, or empty/absent to use the keychain-cached one.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    SignInOutcome SignIn(string @email, string @password, string? @secretKey);
    /// <summary>
    /// Sign out of the active session, keeping this device enrolled (see
    /// [`Client::sign_out`]). A return needs only the password.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    void SignOut();
}
/// <summary>
/// The shell-facing handle: a blocking wrapper over the async [`Client`] facade
/// with its own runtime. Held for the app's lifetime.
/// </summary>
internal class SylvaClient : ISylvaClient, IDisposable {
    protected IntPtr pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public SylvaClient(IntPtr pointer) {
        this.pointer = pointer;
    }

    ~SylvaClient() {
        Destroy();
    }
    /// <summary>
    /// Create a client whose secrets live in the OS keychain under `service`
    /// (e.g. `"sylva-client"`), scoped to the current OS user.
    /// </summary>
    public SylvaClient(string @service) :
        this(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_constructor_sylvaclient_new(FfiConverterString.INSTANCE.Lower(@service), ref _status)
)) {}

    protected void FreeRustArcPtr() {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.uniffi_sylva_sdk_fn_free_sylvaclient(this.pointer, ref status);
        });
    }

    protected IntPtr CloneRustArcPtr() {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            return _UniFFILib.uniffi_sylva_sdk_fn_clone_sylvaclient(this.pointer, ref status);
        });
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter() 
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L) throw new System.ObjectDisposedException(String.Format("'{0}' object has already been destroyed", this.GetType().Name));
            if (count == long.MaxValue) throw new System.OverflowException(String.Format("'{0}' call counter would overflow", this.GetType().Name));

        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter() 
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0) {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<IntPtr> action)
    {
        IncrementCallCounter();
        try {
            action(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<IntPtr, T> func)
    {   
        IncrementCallCounter();
        try {
            return func(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    
    /// <summary>
    /// Discover + verify + connect a server (TOFU). See [`Client::connect`].
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public ConnectInfo Connect(string @host, ushort @discoveryPort) {
        return CallWithPointer(thisPtr => FfiConverterTypeConnectInfo.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_connect(thisPtr, FfiConverterString.INSTANCE.Lower(@host), FfiConverterUInt16.INSTANCE.Lower(@discoveryPort), ref _status)
)));
    }
    
    
    /// <summary>
    /// Create the first owner. Returns the Secret Key to show once.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public Enrollment CreateOwner(string @email, string @displayName, string @password, string @deviceLabel) {
        return CallWithPointer(thisPtr => FfiConverterTypeEnrollment.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_create_owner(thisPtr, FfiConverterString.INSTANCE.Lower(@email), FfiConverterString.INSTANCE.Lower(@displayName), FfiConverterString.INSTANCE.Lower(@password), FfiConverterString.INSTANCE.Lower(@deviceLabel), ref _status)
)));
    }
    
    
    /// <summary>
    /// Enroll this device into the signed-in account.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public DeviceInfo EnrollThisDevice(string @label) {
        return CallWithPointer(thisPtr => FfiConverterTypeDeviceInfo.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_enroll_this_device(thisPtr, FfiConverterString.INSTANCE.Lower(@label), ref _status)
)));
    }
    
    
    /// <summary>
    /// Forget this server entirely — full wipe; re-enroll (Secret Key) to return
    /// (see [`Client::forget_server`]).
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public void ForgetServer() {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_forget_server(thisPtr,  ref _status)
));
    }
    
    
    
    /// <summary>
    /// This account's active devices.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public List<DeviceInfo> ListDevices() {
        return CallWithPointer(thisPtr => FfiConverterSequenceTypeDeviceInfo.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_list_devices(thisPtr,  ref _status)
)));
    }
    
    
    /// <summary>
    /// Auto-resume a prior session on launch (see [`Client::restore`]). Returns the
    /// user id if resumed, else `None` (the shell then shows Connect).
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public string? Restore() {
        return CallWithPointer(thisPtr => FfiConverterOptionalString.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_restore(thisPtr,  ref _status)
)));
    }
    
    
    /// <summary>
    /// Revoke one of this account's devices.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public void RevokeDevice(string @deviceId) {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_revoke_device(thisPtr, FfiConverterString.INSTANCE.Lower(@deviceId), ref _status)
));
    }
    
    
    
    /// <summary>
    /// Sign in (+ unlock). `secret_key` is the user-entered value on a new
    /// device, or empty/absent to use the keychain-cached one.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public SignInOutcome SignIn(string @email, string @password, string? @secretKey) {
        return CallWithPointer(thisPtr => FfiConverterTypeSignInOutcome.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_sign_in(thisPtr, FfiConverterString.INSTANCE.Lower(@email), FfiConverterString.INSTANCE.Lower(@password), FfiConverterOptionalString.INSTANCE.Lower(@secretKey), ref _status)
)));
    }
    
    
    /// <summary>
    /// Sign out of the active session, keeping this device enrolled (see
    /// [`Client::sign_out`]). A return needs only the password.
    /// </summary>
    /// <exception cref="ClientException"></exception>
    public void SignOut() {
        CallWithPointer(thisPtr =>
    _UniffiHelpers.RustCallWithError(FfiConverterTypeClientError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_sylva_sdk_fn_method_sylvaclient_sign_out(thisPtr,  ref _status)
));
    }
    
    
    

    
}
class FfiConverterTypeSylvaClient: FfiConverter<SylvaClient, IntPtr> {
    public static FfiConverterTypeSylvaClient INSTANCE = new FfiConverterTypeSylvaClient();


    public override IntPtr Lower(SylvaClient value) {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override SylvaClient Lift(IntPtr value) {
        return new SylvaClient(value);
    }

    public override SylvaClient Read(BigEndianStream stream) {
        return Lift(new IntPtr(stream.ReadLong()));
    }

    public override int AllocationSize(SylvaClient value) {
        return 8;
    }

    public override void Write(SylvaClient value, BigEndianStream stream) {
        stream.WriteLong(Lower(value).ToInt64());
    }
}



/// <summary>
/// What [`Client::connect`] learned, for the Connect screen's confirm step.
/// </summary>
/// <param name="identity_fingerprint">
/// Hex of the server identity public key (the shell formats it for display).
/// </param>
internal record ConnectInfo (
    string @serverName, 
    /// <summary>
    /// Hex of the server identity public key (the shell formats it for display).
    /// </summary>
    string @identityFingerprint, 
    ushort @grpcPort, 
    TrustStatus @trust
) {
}

class FfiConverterTypeConnectInfo: FfiConverterRustBuffer<ConnectInfo> {
    public static FfiConverterTypeConnectInfo INSTANCE = new FfiConverterTypeConnectInfo();

    public override ConnectInfo Read(BigEndianStream stream) {
        return new ConnectInfo(
            @serverName: FfiConverterString.INSTANCE.Read(stream),
            @identityFingerprint: FfiConverterString.INSTANCE.Read(stream),
            @grpcPort: FfiConverterUInt16.INSTANCE.Read(stream),
            @trust: FfiConverterTypeTrustStatus.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(ConnectInfo value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@serverName)
            + FfiConverterString.INSTANCE.AllocationSize(value.@identityFingerprint)
            + FfiConverterUInt16.INSTANCE.AllocationSize(value.@grpcPort)
            + FfiConverterTypeTrustStatus.INSTANCE.AllocationSize(value.@trust);
    }

    public override void Write(ConnectInfo value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@serverName, stream);
            FfiConverterString.INSTANCE.Write(value.@identityFingerprint, stream);
            FfiConverterUInt16.INSTANCE.Write(value.@grpcPort, stream);
            FfiConverterTypeTrustStatus.INSTANCE.Write(value.@trust, stream);
    }
}



/// <summary>
/// A device row for "My devices".
/// </summary>
internal record DeviceInfo (
    string @deviceId, 
    string @label, 
    string @platform, 
    string @createdAt, 
    bool @revoked
) {
}

class FfiConverterTypeDeviceInfo: FfiConverterRustBuffer<DeviceInfo> {
    public static FfiConverterTypeDeviceInfo INSTANCE = new FfiConverterTypeDeviceInfo();

    public override DeviceInfo Read(BigEndianStream stream) {
        return new DeviceInfo(
            @deviceId: FfiConverterString.INSTANCE.Read(stream),
            @label: FfiConverterString.INSTANCE.Read(stream),
            @platform: FfiConverterString.INSTANCE.Read(stream),
            @createdAt: FfiConverterString.INSTANCE.Read(stream),
            @revoked: FfiConverterBoolean.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(DeviceInfo value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@deviceId)
            + FfiConverterString.INSTANCE.AllocationSize(value.@label)
            + FfiConverterString.INSTANCE.AllocationSize(value.@platform)
            + FfiConverterString.INSTANCE.AllocationSize(value.@createdAt)
            + FfiConverterBoolean.INSTANCE.AllocationSize(value.@revoked);
    }

    public override void Write(DeviceInfo value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@deviceId, stream);
            FfiConverterString.INSTANCE.Write(value.@label, stream);
            FfiConverterString.INSTANCE.Write(value.@platform, stream);
            FfiConverterString.INSTANCE.Write(value.@createdAt, stream);
            FfiConverterBoolean.INSTANCE.Write(value.@revoked, stream);
    }
}



/// <summary>
/// The result of creating the first owner. `secret_key` MUST be shown to the
/// user once for write-down — it is not recoverable.
/// </summary>
internal record Enrollment (
    string @userId, 
    string @secretKey
) {
}

class FfiConverterTypeEnrollment: FfiConverterRustBuffer<Enrollment> {
    public static FfiConverterTypeEnrollment INSTANCE = new FfiConverterTypeEnrollment();

    public override Enrollment Read(BigEndianStream stream) {
        return new Enrollment(
            @userId: FfiConverterString.INSTANCE.Read(stream),
            @secretKey: FfiConverterString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(Enrollment value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.@userId)
            + FfiConverterString.INSTANCE.AllocationSize(value.@secretKey);
    }

    public override void Write(Enrollment value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.@userId, stream);
            FfiConverterString.INSTANCE.Write(value.@secretKey, stream);
    }
}





/// <summary>
/// Errors surfaced to the shell — deliberately coarse (details go to logs, not
/// the UI). Flat variants so the `uniffi::Error` mapping in 3.6b is clean.
/// </summary>
internal class ClientException: UniffiException {
    ClientException() : base() {}
    ClientException(String @Message) : base(@Message) {}

    // Each variant is a nested class
    
    public class NotConnected : ClientException {
        public NotConnected() : base() {}
    }
    
    
    public class NotSignedIn : ClientException {
        public NotSignedIn() : base() {}
    }
    
    
    public class Connect : ClientException {
        public Connect() : base() {}
    }
    
    
    public class IdentityMismatch : ClientException {
        public IdentityMismatch() : base() {}
    }
    
    
    public class Crypto : ClientException {
        public Crypto() : base() {}
    }
    
    
    public class SecretKeyRequired : ClientException {
        public SecretKeyRequired() : base() {}
    }
    
    
    public class Storage : ClientException {
        public Storage() : base() {}
    }
    
    
    public class Server : ClientException {
        public Server() : base() {}
    }
    
    

    
}

class FfiConverterTypeClientError : FfiConverterRustBuffer<ClientException>, CallStatusErrorHandler<ClientException> {
    public static FfiConverterTypeClientError INSTANCE = new FfiConverterTypeClientError();

    public override ClientException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1:
                return new ClientException.NotConnected();
            case 2:
                return new ClientException.NotSignedIn();
            case 3:
                return new ClientException.Connect();
            case 4:
                return new ClientException.IdentityMismatch();
            case 5:
                return new ClientException.Crypto();
            case 6:
                return new ClientException.SecretKeyRequired();
            case 7:
                return new ClientException.Storage();
            case 8:
                return new ClientException.Server();
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeClientError.Read()", value));
        }
    }

    public override int AllocationSize(ClientException value) {
        switch (value) {

            case ClientException.NotConnected variant_value:
                return 4;

            case ClientException.NotSignedIn variant_value:
                return 4;

            case ClientException.Connect variant_value:
                return 4;

            case ClientException.IdentityMismatch variant_value:
                return 4;

            case ClientException.Crypto variant_value:
                return 4;

            case ClientException.SecretKeyRequired variant_value:
                return 4;

            case ClientException.Storage variant_value:
                return 4;

            case ClientException.Server variant_value:
                return 4;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeClientError.AllocationSize()", value));
        }
    }

    public override void Write(ClientException value, BigEndianStream stream) {
        switch (value) {
            case ClientException.NotConnected variant_value:
                stream.WriteInt(1);
                break;
            case ClientException.NotSignedIn variant_value:
                stream.WriteInt(2);
                break;
            case ClientException.Connect variant_value:
                stream.WriteInt(3);
                break;
            case ClientException.IdentityMismatch variant_value:
                stream.WriteInt(4);
                break;
            case ClientException.Crypto variant_value:
                stream.WriteInt(5);
                break;
            case ClientException.SecretKeyRequired variant_value:
                stream.WriteInt(6);
                break;
            case ClientException.Storage variant_value:
                stream.WriteInt(7);
                break;
            case ClientException.Server variant_value:
                stream.WriteInt(8);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeClientError.Write()", value));
        }
    }
}





/// <summary>
/// The outcome of a sign-in attempt.
/// </summary>
internal record SignInOutcome {
    
    public record Success (
        string @userId
    ) : SignInOutcome {}
    
    /// <summary>
    /// The account has a second factor; the shell must complete MFA (not yet
    /// supported by this client — slice 1).
    /// </summary>
    public record MfaRequired: SignInOutcome {}
    
    

    
}

class FfiConverterTypeSignInOutcome : FfiConverterRustBuffer<SignInOutcome>{
    public static FfiConverterRustBuffer<SignInOutcome> INSTANCE = new FfiConverterTypeSignInOutcome();

    public override SignInOutcome Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1:
                return new SignInOutcome.Success(
                    FfiConverterString.INSTANCE.Read(stream)
                );
            case 2:
                return new SignInOutcome.MfaRequired(
                );
            default:
                throw new InternalException(String.Format("invalid enum value '{0}' in FfiConverterTypeSignInOutcome.Read()", value));
        }
    }

    public override int AllocationSize(SignInOutcome value) {
        switch (value) {
            case SignInOutcome.Success variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@userId);
            case SignInOutcome.MfaRequired variant_value:
                return 4;
            default:
                throw new InternalException(String.Format("invalid enum value '{0}' in FfiConverterTypeSignInOutcome.AllocationSize()", value));
        }
    }

    public override void Write(SignInOutcome value, BigEndianStream stream) {
        switch (value) {
            case SignInOutcome.Success variant_value:
                stream.WriteInt(1);
                FfiConverterString.INSTANCE.Write(variant_value.@userId, stream);
                break;
            case SignInOutcome.MfaRequired variant_value:
                stream.WriteInt(2);
                break;
            default:
                throw new InternalException(String.Format("invalid enum value '{0}' in FfiConverterTypeSignInOutcome.Write()", value));
        }
    }
}







/// <summary>
/// Whether this is the first time we've seen a server (pin it) or it matches the
/// stored pin.
/// </summary>
internal enum TrustStatus: int {
    
    FirstContact,
    Trusted
}

class FfiConverterTypeTrustStatus: FfiConverterRustBuffer<TrustStatus> {
    public static FfiConverterTypeTrustStatus INSTANCE = new FfiConverterTypeTrustStatus();

    public override TrustStatus Read(BigEndianStream stream) {
        var value = stream.ReadInt() - 1;
        if (Enum.IsDefined(typeof(TrustStatus), value)) {
            return (TrustStatus)value;
        } else {
            throw new InternalException(String.Format("invalid enum value '{0}' in FfiConverterTypeTrustStatus.Read()", value));
        }
    }

    public override int AllocationSize(TrustStatus value) {
        return 4;
    }

    public override void Write(TrustStatus value, BigEndianStream stream) {
        stream.WriteInt((int)value + 1);
    }
}






class FfiConverterOptionalString: FfiConverterRustBuffer<string?> {
    public static FfiConverterOptionalString INSTANCE = new FfiConverterOptionalString();

    public override string? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(string? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterString.INSTANCE.AllocationSize((string)value);
        }
    }

    public override void Write(string? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterString.INSTANCE.Write((string)value, stream);
        }
    }
}




class FfiConverterSequenceTypeDeviceInfo: FfiConverterRustBuffer<List<DeviceInfo>> {
    public static FfiConverterSequenceTypeDeviceInfo INSTANCE = new FfiConverterSequenceTypeDeviceInfo();

    public override List<DeviceInfo> Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var result = new List<DeviceInfo>(length);
        var readFn = FfiConverterTypeDeviceInfo.INSTANCE.Read;
        for (int i = 0; i < length; i++) {
            result.Add(readFn(stream));
        }
        return result;
    }

    public override int AllocationSize(List<DeviceInfo> value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        var allocationSizeFn = FfiConverterTypeDeviceInfo.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationSizeFn(item));
        return sizeForLength + sizeForItems;
    }

    public override void Write(List<DeviceInfo> value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Count);
        var writerFn = FfiConverterTypeDeviceInfo.INSTANCE.Write;
        value.ForEach(item => writerFn(item, stream));
    }
}
#pragma warning restore 8625
internal static class SylvaSdkMethods {
}

